# Generated by Django 2.2.20 on 2021-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngmt_commands_http', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementcommandjob',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='CREATED', max_length=7),
        ),
    ]
